package io.github.mralex1810.fantasy.entity

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import jakarta.persistence.Table

@Entity
@Table(name = "card_pack")
class CardPack(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,

    @Column(nullable = false)
    var name: String = "",

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "tournament_id", nullable = false)
    var tournament: Tournament? = null,

    @Column(nullable = false)
    var active: Boolean = true,

    @Column(name = "auto_generated", nullable = false)
    var autoGenerated: Boolean = false,

    @Column(name = "price_fantiki", nullable = false)
    var priceFantiki: Long = 0L,

    /** Free opens per user for this pack (only applies when price in fantiki is positive). */
    @Column(name = "free_opens_per_user", nullable = false)
    var freeOpensPerUser: Int = 0,

    /** Max total pack opens per user (incl. free); 0 = unlimited. */
    @Column(name = "max_opens_per_user", nullable = false)
    var maxOpensPerUser: Int = 0,

    @Column(name = "use_all_tournament_players", nullable = false)
    var useAllTournamentPlayers: Boolean = false,

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "card_skin_id", nullable = true)
    var cardSkin: CardSkin? = null,

    @OneToMany(mappedBy = "cardPack")
    var rarityConfigs: MutableList<CardPackRarityConfig> = mutableListOf(),

    @OneToMany(mappedBy = "cardPack")
    var cardPackPlayers: MutableList<CardPackPlayer> = mutableListOf(),
)
