package io.github.mralex1810.fantasy.entity

enum class FantikiTransactionReason {
    INITIAL,
    ADMIN_GRANT,
    ADMIN_CONFISCATE,
    PACK_PURCHASE,
    SERIES_REWARD,
    CARD_RECYCLE,
    CARD_RENEWAL,
    LEGENDARY_UPGRADE,
    EASTER_EGG_BONUS,
    MARKETPLACE_PURCHASE,
    MARKETPLACE_SALE,
    MARKETPLACE_SANCTION_FINE,
    MARKETPLACE_COMPLAINT_REWARD,
    ADMIN_PAIR_BAN,
    ADMIN_CARD_CONFISCATE,
}
