package io.github.mralex1810.fantasy.service

import io.github.mralex1810.fantasy.dto.admin.request.CardPackRarityConfigDto
import io.github.mralex1810.fantasy.dto.admin.request.CreateCardPackRequest
import io.github.mralex1810.fantasy.dto.admin.request.UpdateCardPackRequest
import io.github.mralex1810.fantasy.dto.admin.response.CardPackDto
import io.github.mralex1810.fantasy.dto.admin.response.CardPackRarityConfigResponseDto
import io.github.mralex1810.fantasy.dto.admin.response.OpenPackResultDto
import io.github.mralex1810.fantasy.dto.admin.response.UserCardDto
import io.github.mralex1810.fantasy.entity.Achievement
import io.github.mralex1810.fantasy.entity.CardPack
import io.github.mralex1810.fantasy.entity.CardPackPlayer
import io.github.mralex1810.fantasy.entity.CardPackRarityConfig
import io.github.mralex1810.fantasy.entity.CardTemplate
import io.github.mralex1810.fantasy.entity.CardTemplateAchievement
import io.github.mralex1810.fantasy.entity.FantasyPlayer
import io.github.mralex1810.fantasy.entity.Rarity
import io.github.mralex1810.fantasy.entity.UserCard
import io.github.mralex1810.fantasy.repository.AchievementRepository
import io.github.mralex1810.fantasy.repository.CardPackPlayerRepository
import io.github.mralex1810.fantasy.repository.CardPackRarityConfigRepository
import io.github.mralex1810.fantasy.repository.CardPackRepository
import io.github.mralex1810.fantasy.repository.CardTemplateAchievementRepository
import io.github.mralex1810.fantasy.repository.CardTemplateRepository
import io.github.mralex1810.fantasy.repository.FantasyPlayerRepository
import io.github.mralex1810.fantasy.repository.TournamentPlayerRepository
import io.github.mralex1810.fantasy.repository.TournamentRepository
import io.github.mralex1810.fantasy.repository.UserCardRepository
import org.springframework.http.HttpStatus
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import org.springframework.web.server.ResponseStatusException
import java.time.Instant
import java.util.Random

@Service
class CardPackService(
    private val cardPackRepository: CardPackRepository,
    private val cardPackRarityConfigRepository: CardPackRarityConfigRepository,
    private val cardPackPlayerRepository: CardPackPlayerRepository,
    private val tournamentRepository: TournamentRepository,
    private val tournamentPlayerRepository: TournamentPlayerRepository,
    private val fantasyPlayerRepository: FantasyPlayerRepository,
    private val achievementRepository: AchievementRepository,
    private val cardTemplateRepository: CardTemplateRepository,
    private val cardTemplateAchievementRepository: CardTemplateAchievementRepository,
    private val userCardRepository: UserCardRepository,
    private val userService: UserService,
    private val economyConfigService: EconomyConfigService,
) {

    private val random = Random()

    @Transactional(readOnly = true)
    fun listPacks(tournamentId: Long?): List<CardPackDto> {
        val packs = if (tournamentId != null) {
            if (!tournamentRepository.existsById(tournamentId)) {
                throw ResponseStatusException(HttpStatus.NOT_FOUND, "Tournament $tournamentId not found")
            }
            cardPackRepository.findAllByTournament_IdOrderByIdAsc(tournamentId)
        } else {
            cardPackRepository.findAllByOrderByIdAsc()
        }
        return packs.map { it.toDto(loadPlayerIds(it.id!!)) }
    }

    @Transactional(readOnly = true)
    fun getPack(id: Long): CardPackDto {
        val pack = cardPackRepository.findById(id).orElseThrow {
            ResponseStatusException(HttpStatus.NOT_FOUND, "Card pack $id not found")
        }
        return pack.toDto(cardPackPlayerRepository.findAllByCardPack_Id(id).map { it.fantasyPlayer!!.id!! })
    }

    @Transactional
    fun createPack(request: CreateCardPackRequest): CardPackDto {
        validatePackConfiguration(
            request.rarityConfigs,
            request.useAllTournamentPlayers,
            request.playerIds,
            request.tournamentId,
        )
        val tournament = tournamentRepository.findById(request.tournamentId).orElseThrow {
            ResponseStatusException(HttpStatus.NOT_FOUND, "Tournament ${request.tournamentId} not found")
        }
        val pack = cardPackRepository.save(
            CardPack(
                name = request.name.trim(),
                tournament = tournament,
                active = request.active,
                autoGenerated = request.autoGenerated,
                priceFantiki = request.priceFantiki,
                freeOpensPerUser = request.freeOpensPerUser,
                useAllTournamentPlayers = request.useAllTournamentPlayers,
            ),
        )
        request.rarityConfigs.forEach { dto ->
            cardPackRarityConfigRepository.save(
                CardPackRarityConfig(
                    cardPack = pack,
                    rarity = dto.rarity,
                    cardsCount = dto.cardsCount,
                ),
            )
        }
        if (!request.useAllTournamentPlayers) {
            replacePlayerPool(pack, request.playerIds!!)
        }
        return getPack(pack.id!!)
    }

    @Transactional
    fun updatePack(id: Long, request: UpdateCardPackRequest): CardPackDto {
        val pack = cardPackRepository.findById(id).orElseThrow {
            ResponseStatusException(HttpStatus.NOT_FOUND, "Card pack $id not found")
        }
        request.name?.let { pack.name = it.trim() }
        request.active?.let { pack.active = it }
        request.autoGenerated?.let { pack.autoGenerated = it }
        request.priceFantiki?.let { pack.priceFantiki = it }
        request.freeOpensPerUser?.let { pack.freeOpensPerUser = it }

        val mergedUseAll = request.useAllTournamentPlayers ?: pack.useAllTournamentPlayers
        val currentPlayerIds = cardPackPlayerRepository.findAllByCardPack_Id(id).map { it.fantasyPlayer!!.id!! }
        val mergedPlayerIds = request.playerIds ?: currentPlayerIds

        val configsForValidation = request.rarityConfigs
            ?: pack.rarityConfigs.map { CardPackRarityConfigDto(rarity = it.rarity, cardsCount = it.cardsCount) }
        validatePackConfiguration(
            configsForValidation,
            mergedUseAll,
            if (mergedUseAll) null else mergedPlayerIds,
            pack.tournament!!.id!!,
        )

        request.useAllTournamentPlayers?.let { pack.useAllTournamentPlayers = it }

        request.rarityConfigs?.let { cfg ->
            cardPackRarityConfigRepository.deleteAllByCardPack_Id(id)
            cardPackRarityConfigRepository.flush()
            val newCfgs = cfg.map { dto ->
                cardPackRarityConfigRepository.save(
                    CardPackRarityConfig(
                        cardPack = pack,
                        rarity = dto.rarity,
                        cardsCount = dto.cardsCount,
                    ),
                )
            }
            pack.rarityConfigs.clear()
            pack.rarityConfigs.addAll(newCfgs)
        }

        if (request.useAllTournamentPlayers != null || request.playerIds != null) {
            cardPackPlayerRepository.deleteAllByCardPack_Id(id)
            cardPackPlayerRepository.flush()
            if (!pack.useAllTournamentPlayers) {
                replacePlayerPool(pack, mergedPlayerIds)
            }
        }

        cardPackRepository.save(pack)
        return getPack(id)
    }

    @Transactional
    fun replacePackPlayers(packId: Long, playerIds: List<Long>): CardPackDto {
        val pack = cardPackRepository.findById(packId).orElseThrow {
            ResponseStatusException(HttpStatus.NOT_FOUND, "Card pack $packId not found")
        }
        if (pack.useAllTournamentPlayers) {
            throw ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "Player pool is fixed to all tournament players for this pack",
            )
        }
        validatePlayerIdsForTournament(pack.tournament!!.id!!, playerIds)
        if (playerIds.isEmpty()) {
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "playerIds must not be empty")
        }
        cardPackPlayerRepository.deleteAllByCardPack_Id(packId)
        cardPackPlayerRepository.flush()
        replacePlayerPool(pack, playerIds)
        return getPack(packId)
    }

    /**
     * @param telegramUserId Telegram platform user id (not internal DB id).
     */
    @Transactional
    fun openPack(telegramUserId: Long, packId: Long): OpenPackResultDto {
        val user = userService.getOrCreateAndUpdateProfile(telegramUserId, null, null)
        val pack = cardPackRepository.findByIdWithRarityConfigs(packId)
            ?: throw ResponseStatusException(HttpStatus.NOT_FOUND, "Card pack $packId not found")
        if (!pack.autoGenerated) {
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "Card pack is not auto-generated")
        }
        if (!pack.active) {
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "Card pack is not active")
        }
        val tournamentId = pack.tournament!!.id!!
        val playerPool = buildFantasyPlayerPool(pack, tournamentId)
        if (playerPool.isEmpty()) {
            throw ResponseStatusException(HttpStatus.BAD_REQUEST, "Player pool for this pack is empty")
        }
        val randomAchievements = achievementRepository.findAllByCanAppearOnRandomCardsTrueOrderById()
        val now = Instant.now()
        val drawn = mutableListOf<UserCard>()
        pack.rarityConfigs.forEach { cfg ->
            repeat(cfg.cardsCount) {
                val fantasyPlayer = playerPool[random.nextInt(playerPool.size)]
                val achievements = pickAchievementsForSlot(cfg.rarity, randomAchievements)
                val template = findOrCreateCardTemplate(fantasyPlayer, cfg.rarity, achievements)
                drawn.add(
                    userCardRepository.save(
                        UserCard(
                            telegramUser = user,
                            cardTemplate = template,
                            sourceCardPack = pack,
                            acquiredAt = now,
                            usesRemaining = economyConfigService.getUsesForRarity(cfg.rarity),
                            timesRenewed = 0,
                        ),
                    ),
                )
            }
        }
        return OpenPackResultDto(userCards = drawn.map { it.toUserCardDto() })
    }

    private fun buildFantasyPlayerPool(pack: CardPack, tournamentId: Long): List<FantasyPlayer> {
        return if (pack.useAllTournamentPlayers) {
            val tps = tournamentPlayerRepository.findAllByTournament_IdOrderById(tournamentId)
            if (tps.isEmpty()) {
                emptyList()
            } else {
                tps.map { it.fantasyPlayer!! }
            }
        } else {
            cardPackPlayerRepository.findAllByCardPack_Id(pack.id!!).map { it.fantasyPlayer!! }
        }
    }

    private fun pickAchievementsForSlot(rarity: Rarity, pool: List<Achievement>): List<Achievement> {
        return when (rarity) {
            Rarity.COMMON -> emptyList()
            Rarity.RARE -> {
                if (pool.isEmpty()) {
                    throw ResponseStatusException(
                        HttpStatus.BAD_REQUEST,
                        "No achievements marked for random cards",
                    )
                }
                listOf(pool[random.nextInt(pool.size)])
            }
            Rarity.EPIC -> {
                if (pool.size < 2) {
                    throw ResponseStatusException(
                        HttpStatus.BAD_REQUEST,
                        "Need at least 2 achievements marked for random cards for EPIC slots",
                    )
                }
                pool.shuffled(random).take(2)
            }
            Rarity.LEGENDARY -> throw ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "LEGENDARY cannot be generated from packs",
            )
        }
    }

    private fun findOrCreateCardTemplate(
        fantasyPlayer: FantasyPlayer,
        rarity: Rarity,
        achievements: List<Achievement>,
    ): CardTemplate {
        val wantedIds = achievements.map { it.id }.toSet()
        val candidates = cardTemplateRepository.findAllByFantasyPlayer_IdAndRarity(fantasyPlayer.id!!, rarity)
        val existing = candidates.find { ct ->
            val ids = cardTemplateAchievementRepository.findAchievementIdsByCardTemplateId(ct.id!!).toSet()
            ids == wantedIds
        }
        if (existing != null) {
            return existing
        }
        val saved = cardTemplateRepository.save(
            CardTemplate(
                fantasyPlayer = fantasyPlayer,
                rarity = rarity,
            ),
        )
        achievements.forEach { a ->
            val row = CardTemplateAchievement(
                cardTemplate = saved,
                achievement = a,
                bonusPoints = null,
            )
            cardTemplateAchievementRepository.save(row)
            saved.achievements.add(row)
        }
        return cardTemplateRepository.findById(saved.id!!).orElseThrow()
    }

    private fun replacePlayerPool(pack: CardPack, playerIds: List<Long>) {
        playerIds.forEach { fpId ->
            val fp = fantasyPlayerRepository.findById(fpId).orElseThrow {
                ResponseStatusException(HttpStatus.NOT_FOUND, "Fantasy player $fpId not found")
            }
            cardPackPlayerRepository.save(CardPackPlayer(cardPack = pack, fantasyPlayer = fp))
        }
    }

    private fun loadPlayerIds(packId: Long): List<Long> =
        cardPackPlayerRepository.findAllByCardPack_Id(packId).map { it.fantasyPlayer!!.id!! }

    private fun CardPack.toDto(playerIds: List<Long>): CardPackDto {
        val cfgs = rarityConfigs.map { c ->
            CardPackRarityConfigResponseDto(
                id = c.id!!,
                rarity = c.rarity,
                cardsCount = c.cardsCount,
            )
        }
        return CardPackDto(
            id = id!!,
            name = name,
            tournamentId = tournament!!.id!!,
            active = active,
            autoGenerated = autoGenerated,
            priceFantiki = priceFantiki,
            freeOpensPerUser = freeOpensPerUser,
            useAllTournamentPlayers = useAllTournamentPlayers,
            playerIds = playerIds,
            rarityConfigs = cfgs,
        )
    }

    private fun UserCard.toUserCardDto() = UserCardDto(
        id = id!!,
        telegramUserId = telegramUser!!.telegramId,
        cardTemplateId = cardTemplate!!.id!!,
        acquiredAt = acquiredAt,
        sourceCardPackId = sourceCardPack?.id,
    )

    companion object {
        fun validateRarityConfigs(configs: List<CardPackRarityConfigDto>) {
            if (configs.isEmpty()) {
                throw ResponseStatusException(
                    HttpStatus.BAD_REQUEST,
                    "At least one rarity config is required",
                )
            }
            val duplicates = configs.groupingBy { it.rarity }.eachCount().filter { it.value > 1 }.keys
            if (duplicates.isNotEmpty()) {
                throw ResponseStatusException(
                    HttpStatus.BAD_REQUEST,
                    "Duplicate rarity entries: $duplicates",
                )
            }
            configs.forEach { c ->
                if (c.cardsCount <= 0) {
                    throw ResponseStatusException(
                        HttpStatus.BAD_REQUEST,
                        "cardsCount must be positive for rarity ${c.rarity}",
                    )
                }
                if (c.rarity == Rarity.LEGENDARY) {
                    throw ResponseStatusException(
                        HttpStatus.BAD_REQUEST,
                        "LEGENDARY is not allowed in card packs",
                    )
                }
            }
        }

        fun validatePackConfiguration(
            configs: List<CardPackRarityConfigDto>,
            useAllTournamentPlayers: Boolean,
            playerIds: List<Long>?,
            tournamentId: Long,
            tournamentPlayerRepository: TournamentPlayerRepository,
        ) {
            validateRarityConfigs(configs)
            if (useAllTournamentPlayers) {
                if (tournamentPlayerRepository.countByTournament_Id(tournamentId) == 0L) {
                    throw ResponseStatusException(HttpStatus.BAD_REQUEST, "Tournament has no players")
                }
            } else {
                val ids = playerIds ?: emptyList()
                if (ids.isEmpty()) {
                    throw ResponseStatusException(
                        HttpStatus.BAD_REQUEST,
                        "playerIds is required when useAllTournamentPlayers is false",
                    )
                }
                ids.forEach { fpId ->
                    if (!tournamentPlayerRepository.existsByTournament_IdAndFantasyPlayer_Id(tournamentId, fpId)) {
                        throw ResponseStatusException(
                            HttpStatus.BAD_REQUEST,
                            "Fantasy player $fpId is not registered in tournament $tournamentId",
                        )
                    }
                }
            }
        }
    }

    private fun validatePackConfiguration(
        configs: List<CardPackRarityConfigDto>,
        useAllTournamentPlayers: Boolean,
        playerIds: List<Long>?,
        tournamentId: Long,
    ) {
        validatePackConfiguration(
            configs,
            useAllTournamentPlayers,
            playerIds,
            tournamentId,
            tournamentPlayerRepository,
        )
    }

    private fun validatePlayerIdsForTournament(tournamentId: Long, playerIds: List<Long>) {
        playerIds.forEach { fpId ->
            if (!tournamentPlayerRepository.existsByTournament_IdAndFantasyPlayer_Id(tournamentId, fpId)) {
                throw ResponseStatusException(
                    HttpStatus.BAD_REQUEST,
                    "Fantasy player $fpId is not registered in tournament $tournamentId",
                )
            }
        }
    }
}
