package io.github.mralex1810.fantasy.dto.admin.response

import io.github.mralex1810.fantasy.entity.OccurrenceType
import io.github.mralex1810.fantasy.entity.Rarity
import io.github.mralex1810.fantasy.entity.SeriesStatus
import io.github.mralex1810.fantasy.entity.TournamentKind
import io.github.mralex1810.fantasy.entity.TournamentStatus
import java.time.Instant

data class ActiveSeriesBriefDto(
    val id: Long,
    val name: String,
    val status: SeriesStatus,
)

data class TournamentDto(
    val id: Long,
    val name: String,
    val description: String?,
    val status: TournamentStatus,
    val kind: TournamentKind,
    val polemicaCompetitionId: Long?,
    val createdAt: Instant,
    /** Populated on list tournaments; empty on create/update responses. */
    val activeSeries: List<ActiveSeriesBriefDto> = emptyList(),
)

data class TournamentDetailDto(
    val id: Long,
    val name: String,
    val description: String?,
    val status: TournamentStatus,
    val kind: TournamentKind,
    val polemicaCompetitionId: Long?,
    val createdAt: Instant,
    val players: List<TournamentPlayerDto>,
)

data class TournamentPlayerDto(
    val id: Long,
    val tournamentId: Long,
    val fantasyPlayerId: Long,
    val polemicaUserId: Long,
    val nickname: String,
    val photoUrl: String?,
    /** If true, omitted from random pack player pools for this tournament. */
    val excludedFromPackPool: Boolean,
)

data class SeriesDto(
    val id: Long,
    val tournamentId: Long,
    val name: String,
    val namePrefix: String?,
    val gameNumFrom: Long?,
    val gameNumTo: Long?,
    val status: SeriesStatus,
    val startsAt: Instant,
    val teamDeadline: Instant,
    val finalized: Boolean,
    /** Rows in `series_game` (synced from Polemica). */
    val syncedGamesCount: Long,
    /** Subset with `scored = true` (calculated fantasy points). */
    val scoredGamesCount: Long,
    /** `tournament_player.id` for players assigned to this series */
    val tournamentPlayerIds: List<Long>,
)

data class AchievementAdminDto(
    val id: String,
    val name: String,
    val description: String?,
    val bonusPoints: Double,
    val occurrenceType: OccurrenceType,
    val applicableRoles: List<String>,
    val canAppearOnRandomCards: Boolean,
)

data class CardTemplateAchievementDto(
    val id: Long,
    val achievementId: String,
    val achievementName: String,
    /** Effective bonus (per-card override or achievement default). */
    val bonusPoints: Double,
)

data class CardTemplateDto(
    val id: Long,
    val fantasyPlayerId: Long,
    val rarity: Rarity,
    val imageUrl: String?,
    val description: String?,
    val achievements: List<CardTemplateAchievementDto>,
)

data class CardPackRarityConfigResponseDto(
    val id: Long,
    val rarity: Rarity,
    val cardsCount: Int,
)

data class CardPackDto(
    val id: Long,
    val name: String,
    val tournamentId: Long,
    val active: Boolean,
    val autoGenerated: Boolean,
    val priceFantiki: Long,
    val freeOpensPerUser: Int,
    /** Max total opens per user; 0 = unlimited. */
    val maxOpensPerUser: Int,
    val achievementIds: List<String>,
    val useAllTournamentPlayers: Boolean,
    val playerIds: List<Long>,
    val rarityConfigs: List<CardPackRarityConfigResponseDto>,
)

data class UserCardDto(
    val id: Long,
    val telegramUserId: Long,
    val cardTemplateId: Long,
    val acquiredAt: Instant,
    val sourceCardPackId: Long?,
)

data class OpenPackResultDto(
    val userCards: List<UserCardDto>,
)

data class EconomyConfigItemDto(
    val key: String,
    val value: String,
    val description: String?,
)

data class ApiErrorBody(
    val message: String,
    val fieldErrors: Map<String, String>? = null,
)

/** Admin list row; [cardsInSeries] is null when no series filter was requested. */
data class AdminUserListItemDto(
    val id: Long,
    val telegramId: Long,
    val username: String?,
    val displayName: String?,
    val fantiki: Long,
    val cardsInSeries: Long?,
)
