package io.github.mralex1810.fantasy.dto.admin.response

import io.github.mralex1810.fantasy.entity.CardPackOpeningMode
import io.github.mralex1810.fantasy.entity.OccurrenceType
import io.github.mralex1810.fantasy.entity.Rarity
import io.github.mralex1810.fantasy.entity.SeriesStatus
import io.github.mralex1810.fantasy.entity.TournamentKind
import io.github.mralex1810.fantasy.entity.TournamentStatus
import java.time.Instant
import java.time.LocalDate

data class ActiveSeriesBriefDto(
    val id: Long,
    val name: String,
    val status: SeriesStatus,
)

data class TournamentDto(
    val id: Long,
    val name: String,
    val description: String?,
    val status: TournamentStatus,
    val kind: TournamentKind,
    val polemicaCompetitionId: Long?,
    val createdAt: Instant,
    /** Populated on list tournaments; empty on create/update responses. */
    val activeSeries: List<ActiveSeriesBriefDto> = emptyList(),
)

data class TournamentDetailDto(
    val id: Long,
    val name: String,
    val description: String?,
    val status: TournamentStatus,
    val kind: TournamentKind,
    val polemicaCompetitionId: Long?,
    val createdAt: Instant,
    val players: List<TournamentPlayerDto>,
)

data class TournamentPlayerDto(
    val id: Long,
    val tournamentId: Long,
    val fantasyPlayerId: Long,
    val polemicaUserId: Long,
    val nickname: String,
    val photoUrl: String?,
    /** If true, omitted from random pack player pools for this tournament. */
    val excludedFromPackPool: Boolean,
)

data class FantasyPlayerAdminDto(
    val id: Long,
    val polemicaUserId: Long,
    val nickname: String,
    val photoUrl: String?,
    val tournamentIds: List<Long>,
    val tournamentCount: Long,
    val cardTemplateCount: Long,
)

data class SeriesDto(
    val id: Long,
    val tournamentId: Long,
    val name: String,
    val publicNumber: Long,
    val namePrefix: String?,
    val gameNumFrom: Long?,
    val gameNumTo: Long?,
    /** POLEMICA_COMPETITION filter: 0/1/2, null = all phases. */
    val gamePhase: Int?,
    /** STANDALONE filter: include games from this calendar day (`started`); null = all days. */
    val gameStartedOn: LocalDate?,
    val status: SeriesStatus,
    val startsAt: Instant,
    val teamDeadline: Instant,
    val finalized: Boolean,
    /** Rows in `series_game` (synced from Polemica). */
    val syncedGamesCount: Long,
    /** Subset with `scored = true` (calculated fantasy points). */
    val scoredGamesCount: Long,
    /** `tournament_player.id` for players assigned to this series */
    val tournamentPlayerIds: List<Long>,
    /** Optional replacement Polemica user id by `tournament_player.id`. */
    val replacementPolemicaUserIds: Map<Long, Long> = emptyMap(),
)

data class AdminSeriesGameDto(
    val id: Long,
    val polemicaGameId: Long,
    val displayName: String,
    val gameName: String,
    val gameNum: Int?,
    val table: Int?,
    val phase: Int?,
    val playedAt: Instant?,
    val finished: Boolean,
    val scored: Boolean,
)

data class SeriesPlayerMarketplaceUnlistResultDto(
    val tournamentPlayerId: Long,
    val fantasyPlayerId: Long,
    val playerNickname: String,
    val cancelledListings: Int,
)

data class PerkAdminDto(
    val id: String,
    val name: String,
    val description: String?,
    val bonusPoints: Double,
    val occurrenceType: OccurrenceType,
    val applicableRoles: List<String>,
    val canAppearOnRandomCards: Boolean,
)

data class CardTemplatePerkDto(
    val id: Long,
    val perkId: String,
    val perkName: String,
    /** Effective bonus (per-card override or perk default). */
    val bonusPoints: Double,
)

data class CardTemplateDto(
    val id: Long,
    val fantasyPlayerId: Long,
    val rarity: Rarity,
    val imageUrl: String?,
    val description: String?,
    val perks: List<CardTemplatePerkDto>,
)

data class CardPackRarityConfigResponseDto(
    val id: Long,
    val rarity: Rarity,
    val cardsCount: Int,
)

data class CardSkinDto(
    val id: Long,
    val code: String,
    val name: String,
)

data class CardPackDto(
    val id: Long,
    val name: String,
    val tournamentId: Long,
    val active: Boolean,
    val autoGenerated: Boolean,
    val openingMode: CardPackOpeningMode,
    val priceFantiki: Long,
    val freeOpensPerUser: Int,
    /** Max total opens per user; 0 = unlimited. */
    val maxOpensPerUser: Int,
    val perkIds: List<String>,
    val useAllTournamentPlayers: Boolean,
    val playerIds: List<Long>,
    val rarityConfigs: List<CardPackRarityConfigResponseDto>,
    val skinId: Long?,
    val skinCode: String?,
)

data class UserCardDto(
    val id: Long,
    val telegramUserId: Long,
    val cardTemplateId: Long,
    val acquiredAt: Instant,
    val sourceCardPackId: Long?,
)

data class OpenPackResultDto(
    val userCards: List<UserCardDto>,
)

data class EconomyConfigItemDto(
    val key: String,
    val value: String,
    val description: String?,
)

enum class AdminRole {
    ADMIN,
    MODERATOR,
}

data class AdminMeDto(
    val username: String,
    val role: AdminRole,
)

data class ApiErrorBody(
    val message: String,
    val fieldErrors: Map<String, String>? = null,
)

/** Admin list row; [cardsInSeries] is null when no series filter was requested. */
data class AdminUserListItemDto(
    val id: Long,
    val telegramId: Long,
    val username: String?,
    val displayName: String?,
    val fantiki: Long,
    val botBlocked: Boolean,
    val cardsInSeries: Long?,
)

data class FantikiAdjustmentDto(
    val id: Long,
    val createdAt: java.time.Instant,
    val telegramId: Long,
    val amount: Long,
    val reason: String,
    val adminReason: String?,
)

data class PagedFantikiAdjustmentsDto(
    val content: List<FantikiAdjustmentDto>,
    val page: Int,
    val size: Int,
    val totalElements: Long,
    val totalPages: Int,
)
