import {
  Alert,
  App,
  Button,
  Form,
  Input,
  InputNumber,
  Modal,
  Select,
  Space,
  Switch,
  Table,
  Tag,
  Typography,
} from 'antd'
import { MinusCircleOutlined, PlusOutlined } from '@ant-design/icons'
import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { listPerks } from '../api/perks'
import { createCardPack, listCardPacks, listCardSkins, updateCardPack } from '../api/packs'
import { listTournaments, getTournament } from '../api/tournaments'
import type { CardPackOpeningMode, Rarity } from '../api/types'

const RARITY_TIERS: Rarity[] = ['COMMON', 'RARE', 'EPIC']

export function CardPacksPage() {
  const { message } = App.useApp()
  const [tournamentFilter, setTournamentFilter] = useState<number | undefined>()
  const [createOpen, setCreateOpen] = useState(false)
  const [editId, setEditId] = useState<number | null>(null)

  const [createForm] = Form.useForm<{
    name: string
    tournamentId: number
    active: boolean
    autoGenerated: boolean
    openingMode: CardPackOpeningMode
    priceFantiki: number
    freeOpensPerUser: number
    maxOpensPerUser: number
    perkIds: string[]
    useAllTournamentPlayers: boolean
    skinId: number | null
    playerIds: number[]
    rarityConfigs: { rarity: Rarity; cardsCount: number }[]
  }>()

  const tq = useQuery({
    queryKey: ['admin', 'tournaments'],
    queryFn: listTournaments,
  })

  const perksQ = useQuery({
    queryKey: ['admin', 'perks'],
    queryFn: listPerks,
  })

  const skinsQ = useQuery({
    queryKey: ['admin', 'card-skins'],
    queryFn: listCardSkins,
  })

  const pq = useQuery({
    queryKey: ['admin', 'card-packs', tournamentFilter],
    queryFn: () => listCardPacks(tournamentFilter),
  })

  const createTournamentId = Form.useWatch('tournamentId', createForm)
  const createAuto = Form.useWatch('autoGenerated', createForm)
  const createOpeningMode = Form.useWatch('openingMode', createForm)
  const createUseAll = Form.useWatch('useAllTournamentPlayers', createForm)

  const createPlayersQ = useQuery({
    queryKey: ['admin', 'tournament-players', createTournamentId],
    queryFn: () => getTournament(createTournamentId!),
    enabled: createOpen && createTournamentId != null,
  })

  const editFormTournamentId = pq.data?.find((p) => p.id === editId)?.tournamentId

  const editPlayersQ = useQuery({
    queryKey: ['admin', 'tournament-players', editFormTournamentId],
    queryFn: () => getTournament(editFormTournamentId!),
    enabled: editId != null && editFormTournamentId != null,
  })

  const createMut = useMutation({
    mutationFn: createCardPack,
    onSuccess: () => {
      message.success('Pack created')
      setCreateOpen(false)
      createForm.resetFields()
      void pq.refetch()
    },
    onError: (e: Error) => message.error(e.message),
  })

  const updatePackMut = useMutation({
    mutationFn: (args: { id: number; body: Parameters<typeof updateCardPack>[1] }) =>
      updateCardPack(args.id, args.body),
    onSuccess: () => {
      message.success('Pack updated')
      setEditId(null)
      void pq.refetch()
    },
    onError: (e: Error) => message.error(e.message),
  })

  const editing = pq.data?.find((p) => p.id === editId)
  const sortedPacks = useMemo(
    () =>
      [...(pq.data ?? [])].sort(
        (a, b) => Number(b.active) - Number(a.active),
      ),
    [pq.data],
  )

  const rarityOptions = useMemo(
    () => RARITY_TIERS.map((r) => ({ value: r, label: r })),
    [],
  )

  useEffect(() => {
    if (!createOpen) return
    createForm.setFieldsValue({
      active: true,
      autoGenerated: false,
      openingMode: 'INSTANT',
      priceFantiki: 0,
      freeOpensPerUser: 0,
      maxOpensPerUser: 0,
      perkIds: [],
      useAllTournamentPlayers: true,
      skinId: null,
      playerIds: [],
      rarityConfigs: [{ rarity: 'COMMON', cardsCount: 1 }],
    })
  }, [createOpen, createForm])

  useEffect(() => {
    if (createOpeningMode === 'CHOOSE') {
      createForm.setFieldsValue({ autoGenerated: true })
    }
  }, [createOpeningMode, createForm])

  return (
    <div>
      <Typography.Title level={3}>Card packs</Typography.Title>
      <Space style={{ marginBottom: 16 }}>
        <Select
          allowClear
          placeholder="Filter by tournament"
          style={{ width: 280 }}
          options={tq.data?.map((t) => ({
            value: t.id,
            label: `${t.id}: ${t.name}`,
          }))}
          value={tournamentFilter}
          onChange={(v) => setTournamentFilter(v)}
        />
        <Button type="primary" onClick={() => setCreateOpen(true)}>
          New pack
        </Button>
      </Space>

      <Table
        rowKey="id"
        loading={pq.isLoading}
        dataSource={sortedPacks}
        pagination={false}
        scroll={{ x: true }}
        columns={[
          { title: 'ID', dataIndex: 'id', width: 70 },
          { title: 'Name', dataIndex: 'name' },
          { title: 'Tournament', dataIndex: 'tournamentId' },
          {
            title: 'Skin',
            width: 170,
            render: (_, row) => (row.skinCode ? <Tag color="gold">{row.skinCode}</Tag> : '—'),
          },
          {
            title: 'Auto',
            dataIndex: 'autoGenerated',
            width: 80,
            render: (a: boolean) =>
              a ? <Tag color="blue">yes</Tag> : <Tag>no</Tag>,
          },
          {
            title: 'Mode',
            dataIndex: 'openingMode',
            width: 110,
            render: (mode: CardPackOpeningMode) =>
              mode === 'CHOOSE' ? <Tag color="purple">choose</Tag> : <Tag>instant</Tag>,
          },
          {
            title: 'Price (fantiki)',
            dataIndex: 'priceFantiki',
            width: 120,
          },
          {
            title: 'Free opens / user',
            dataIndex: 'freeOpensPerUser',
            width: 130,
          },
          {
            title: 'Max opens / user',
            dataIndex: 'maxOpensPerUser',
            width: 120,
            render: (n: number) => (n > 0 ? n : '—'),
          },
          {
            title: 'All tour. players',
            dataIndex: 'useAllTournamentPlayers',
            width: 130,
            render: (v: boolean) => (v ? <Tag color="green">yes</Tag> : <Tag>no</Tag>),
          },
          {
            title: 'Player pool',
            dataIndex: 'playerIds',
            ellipsis: true,
            render: (ids: number[], row) =>
              row.useAllTournamentPlayers
                ? '—'
                : (ids?.length ? ids.join(', ') : '—'),
          },
          {
            title: 'Active',
            dataIndex: 'active',
            render: (a: boolean) => (a ? <Tag color="green">yes</Tag> : <Tag>no</Tag>),
          },
          {
            title: 'Configs',
            dataIndex: 'rarityConfigs',
            render: (c: { rarity: string; cardsCount: number }[]) =>
              c?.map((x) => `${x.rarity}×${x.cardsCount}`).join(', ') ?? '',
          },
          {
            title: '',
            key: 'e',
            render: (_, row) => (
              <Button type="link" onClick={() => setEditId(row.id)}>
                Edit
              </Button>
            ),
          },
        ]}
      />

      <Modal
        title="Create pack"
        open={createOpen}
        onCancel={() => setCreateOpen(false)}
        footer={null}
        destroyOnHidden
        width={720}
      >
        <Form
          form={createForm}
          layout="vertical"
          onFinish={(v) => {
            const body = {
              name: v.name,
              tournamentId: v.tournamentId,
              active: v.active ?? true,
              autoGenerated: v.autoGenerated ?? false,
              openingMode: v.openingMode ?? 'INSTANT',
              priceFantiki: v.priceFantiki ?? 0,
              freeOpensPerUser: v.freeOpensPerUser ?? 0,
              maxOpensPerUser: v.maxOpensPerUser ?? 0,
              perkIds: v.perkIds ?? [],
              useAllTournamentPlayers: v.useAllTournamentPlayers ?? false,
              skinId: v.skinId ?? null,
              playerIds: v.useAllTournamentPlayers ? null : v.playerIds,
              rarityConfigs: v.rarityConfigs,
            }
            createMut.mutate(body)
          }}
        >
          <Form.Item name="name" label="Name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item
            name="tournamentId"
            label="Tournament"
            rules={[{ required: true }]}
          >
            <Select
              options={tq.data?.map((t) => ({
                value: t.id,
                label: `${t.id}: ${t.name}`,
              }))}
              onChange={() => {
                createForm.setFieldsValue({ playerIds: [] })
              }}
            />
          </Form.Item>
          <Form.Item name="active" label="Active" valuePropName="checked">
            <Switch />
          </Form.Item>
          <Form.Item name="openingMode" label="Opening mode">
            <Select
              options={[
                { value: 'INSTANT', label: 'Instant' },
                { value: 'CHOOSE', label: 'Choose: 3 variants, pick 1' },
              ]}
            />
          </Form.Item>
          <Form.Item
            name="autoGenerated"
            label="Auto-generate cards on open"
            valuePropName="checked"
          >
            <Switch disabled={createOpeningMode === 'CHOOSE'} />
          </Form.Item>
          {createOpeningMode === 'CHOOSE' ? (
            <Alert
              type="info"
              showIcon
              style={{ marginBottom: 16 }}
              message="CHOOSE packs are fixed in V1: 3 generated variants, user selects 1. They must be auto-generated."
            />
          ) : null}
          {createAuto ? (
            <Alert
              type="info"
              showIcon
              style={{ marginBottom: 16 }}
              message="Auto packs: Rare adds 1 random perk, Epic adds 2. Legendary is not available."
            />
          ) : null}
          <Form.Item name="priceFantiki" label="Price (fantiki)">
            <InputNumber min={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item
            name="freeOpensPerUser"
            label="Бесплатных открытий на пользователя"
            tooltip="Считается только для пака с ценой выше 0. Для каждого пользователя отдельно."
          >
            <InputNumber min={0} precision={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item
            name="maxOpensPerUser"
            label="Макс. открытий на пользователя (всего)"
            tooltip="Лимит всех открытий этого пака (включая бесплатные). 0 — без лимита."
          >
            <InputNumber min={0} precision={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item
            name="perkIds"
            label="Пул перков для RNG (пусто = глобальный пул)"
            tooltip="Для авто-паков: редкие/эпик слоты берут перки только из выбранного списка."
          >
            <Select
              mode="multiple"
              allowClear
              loading={perksQ.isLoading}
              placeholder="Пусто — как в глобальном каталоге (can appear on random cards)"
              options={perksQ.data?.map((a) => ({
                value: a.id,
                label: `${a.id} — ${a.name}`,
              }))}
            />
          </Form.Item>
          <Form.Item name="skinId" label="Skin (optional)">
            <Select
              allowClear
              loading={skinsQ.isLoading}
              placeholder="Default visual (no skin)"
              options={skinsQ.data?.map((s) => ({
                value: s.id,
                label: `${s.name} (${s.code})`,
              }))}
            />
          </Form.Item>
          <Form.Item
            name="useAllTournamentPlayers"
            label="Use all tournament players as pool"
            valuePropName="checked"
          >
            <Switch />
          </Form.Item>
          {!createUseAll ? (
            <Form.Item
              name="playerIds"
              label="Player pool (fantasy player ids)"
              rules={[
                {
                  validator: (_, val: number[]) =>
                    val?.length
                      ? Promise.resolve()
                      : Promise.reject(new Error('Pick at least one player')),
                },
              ]}
            >
              <Select
                mode="multiple"
                allowClear
                loading={createPlayersQ.isLoading}
                placeholder="Players registered in this tournament"
                options={createPlayersQ.data?.players.map((p) => ({
                  value: p.fantasyPlayerId,
                  label: `#${p.fantasyPlayerId} ${p.nickname}`,
                }))}
              />
            </Form.Item>
          ) : null}
          <Typography.Text strong>Rarity configs (count per tier)</Typography.Text>
          <Form.List
            name="rarityConfigs"
            rules={[
              {
                validator: async (_, names) => {
                  if (!names || names.length < 1) {
                    return Promise.reject(new Error('Add at least one config'))
                  }
                },
              },
            ]}
          >
            {(fields, { add, remove }) => (
              <>
                {fields.map(({ key, name, ...rest }) => (
                  <Space key={key} align="baseline" wrap>
                    <Form.Item
                      {...rest}
                      name={[name, 'rarity']}
                      rules={[{ required: true }]}
                    >
                      <Select options={rarityOptions} placeholder="Rarity" />
                    </Form.Item>
                    <Form.Item
                      {...rest}
                      name={[name, 'cardsCount']}
                      rules={[{ required: true }]}
                    >
                      <InputNumber min={1} placeholder="count" />
                    </Form.Item>
                    <MinusCircleOutlined onClick={() => remove(name)} />
                  </Space>
                ))}
                <Form.Item>
                  <Button
                    type="dashed"
                    onClick={() => add()}
                    icon={<PlusOutlined />}
                  >
                    Add rarity row
                  </Button>
                </Form.Item>
              </>
            )}
          </Form.List>
          <Form.Item>
            <Button type="primary" htmlType="submit" loading={createMut.isPending}>
              Create
            </Button>
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        title="Edit pack"
        open={editId != null}
        onCancel={() => setEditId(null)}
        footer={null}
        destroyOnHidden
        width={720}
      >
        {editing && (
          <EditPackForm
            key={editing.id}
            editing={editing}
            tournamentPlayers={editPlayersQ.data?.players}
            playersLoading={editPlayersQ.isLoading}
            rarityOptions={rarityOptions}
            loading={updatePackMut.isPending}
            onSubmit={(body) => updatePackMut.mutate({ id: editing.id, body })}
            perkOptions={perksQ.data}
            perksLoading={perksQ.isLoading}
            skins={skinsQ.data}
            skinsLoading={skinsQ.isLoading}
          />
        )}
      </Modal>
    </div>
  )
}

function EditPackForm({
  editing,
  tournamentPlayers,
  playersLoading,
  rarityOptions,
  loading,
  perkOptions,
  perksLoading,
  skins,
  skinsLoading,
  onSubmit,
}: {
  editing: {
    name: string
    active: boolean
    autoGenerated: boolean
    openingMode: CardPackOpeningMode
    priceFantiki: number
    freeOpensPerUser: number
    maxOpensPerUser: number
    perkIds: string[]
    useAllTournamentPlayers: boolean
    skinId: number | null
    playerIds: number[]
    rarityConfigs: { rarity: Rarity; cardsCount: number }[]
  }
  tournamentPlayers?: { fantasyPlayerId: number; nickname: string }[]
  playersLoading: boolean
  rarityOptions: { value: Rarity; label: string }[]
  loading: boolean
  perkOptions: { id: string; name: string }[] | undefined
  perksLoading: boolean
  skins: { id: number; code: string; name: string }[] | undefined
  skinsLoading: boolean
  onSubmit: (body: {
    name: string
    active: boolean
    autoGenerated: boolean
    openingMode: CardPackOpeningMode
    priceFantiki: number
    freeOpensPerUser: number
    maxOpensPerUser: number
    perkIds: string[]
    useAllTournamentPlayers: boolean
    skinId: number | null
    playerIds: number[] | null
    rarityConfigs: { rarity: Rarity; cardsCount: number }[]
  }) => void
}) {
  const [form] = Form.useForm<{
    name: string
    active: boolean
    autoGenerated: boolean
    openingMode: CardPackOpeningMode
    priceFantiki: number
    freeOpensPerUser: number
    maxOpensPerUser: number
    perkIds: string[]
    useAllTournamentPlayers: boolean
    skinId: number | null
    playerIds: number[]
    rarityConfigs: { rarity: Rarity; cardsCount: number }[]
  }>()

  const auto = Form.useWatch('autoGenerated', form)
  const openingMode = Form.useWatch('openingMode', form)

  useEffect(() => {
    if (openingMode === 'CHOOSE') {
      form.setFieldsValue({ autoGenerated: true })
    }
  }, [openingMode, form])
  const useAll = Form.useWatch('useAllTournamentPlayers', form)

  useEffect(() => {
    form.setFieldsValue({
      name: editing.name,
      active: editing.active,
      autoGenerated: editing.autoGenerated,
      openingMode: editing.openingMode,
      priceFantiki: editing.priceFantiki,
      freeOpensPerUser: editing.freeOpensPerUser,
      maxOpensPerUser: editing.maxOpensPerUser,
      perkIds: editing.perkIds ?? [],
      useAllTournamentPlayers: editing.useAllTournamentPlayers,
      skinId: editing.skinId,
      playerIds: editing.playerIds ?? [],
      rarityConfigs: editing.rarityConfigs.map((c) => ({
        rarity: c.rarity,
        cardsCount: c.cardsCount,
      })),
    })
  }, [editing, form])

  return (
    <Form
      form={form}
      layout="vertical"
      onFinish={(v) => {
        onSubmit({
          name: v.name,
          active: v.active,
          autoGenerated: v.autoGenerated,
          openingMode: v.openingMode,
          priceFantiki: v.priceFantiki ?? 0,
          freeOpensPerUser: v.freeOpensPerUser ?? 0,
          maxOpensPerUser: v.maxOpensPerUser ?? 0,
          perkIds: v.perkIds ?? [],
          useAllTournamentPlayers: v.useAllTournamentPlayers,
          skinId: v.skinId ?? null,
          playerIds: v.useAllTournamentPlayers ? null : v.playerIds,
          rarityConfigs: v.rarityConfigs,
        })
      }}
    >
      <Form.Item name="name" label="Name" rules={[{ required: true }]}>
        <Input />
      </Form.Item>
      <Form.Item name="active" label="Active" valuePropName="checked">
        <Switch />
      </Form.Item>
      <Form.Item name="openingMode" label="Opening mode">
        <Select
          options={[
            { value: 'INSTANT', label: 'Instant' },
            { value: 'CHOOSE', label: 'Choose: 3 variants, pick 1' },
          ]}
        />
      </Form.Item>
      <Form.Item
        name="autoGenerated"
        label="Auto-generate cards on open"
        valuePropName="checked"
      >
        <Switch disabled={openingMode === 'CHOOSE'} />
      </Form.Item>
      {openingMode === 'CHOOSE' ? (
        <Alert
          type="info"
          showIcon
          style={{ marginBottom: 16 }}
          message="CHOOSE packs are fixed in V1: 3 generated variants, user selects 1. They must be auto-generated."
        />
      ) : null}
      {auto ? (
        <Alert
          type="info"
          showIcon
          style={{ marginBottom: 16 }}
          message="Auto packs: Rare adds 1 random perk, Epic adds 2. Legendary is not available."
        />
      ) : null}
      <Form.Item name="priceFantiki" label="Price (fantiki)">
        <InputNumber min={0} style={{ width: '100%' }} />
      </Form.Item>
      <Form.Item
        name="freeOpensPerUser"
        label="Бесплатных открытий на пользователя"
        tooltip="Считается только для пака с ценой выше 0. Для каждого пользователя отдельно."
      >
        <InputNumber min={0} precision={0} style={{ width: '100%' }} />
      </Form.Item>
      <Form.Item
        name="maxOpensPerUser"
        label="Макс. открытий на пользователя (всего)"
        tooltip="Лимит всех открытий этого пака (включая бесплатные). 0 — без лимита."
      >
        <InputNumber min={0} precision={0} style={{ width: '100%' }} />
      </Form.Item>
      <Form.Item
        name="perkIds"
        label="Пул перков для RNG (пусто = глобальный пул)"
        tooltip="Для авто-паков: редкие/эпик слоты берут перки только из выбранного списка."
      >
        <Select
          mode="multiple"
          allowClear
          loading={perksLoading}
          placeholder="Пусто — как в глобальном каталоге (can appear on random cards)"
          options={perkOptions?.map((a) => ({
            value: a.id,
            label: `${a.id} — ${a.name}`,
          }))}
        />
      </Form.Item>
      <Form.Item name="skinId" label="Skin (optional)">
        <Select
          allowClear
          loading={skinsLoading}
          placeholder="Default visual (no skin)"
          options={skins?.map((s) => ({
            value: s.id,
            label: `${s.name} (${s.code})`,
          }))}
        />
      </Form.Item>
      <Form.Item
        name="useAllTournamentPlayers"
        label="Use all tournament players as pool"
        valuePropName="checked"
      >
        <Switch />
      </Form.Item>
      {!useAll ? (
        <Form.Item
          name="playerIds"
          label="Player pool (fantasy player ids)"
          rules={[
            {
              validator: (_, val: number[]) =>
                val?.length
                  ? Promise.resolve()
                  : Promise.reject(new Error('Pick at least one player')),
            },
          ]}
        >
          <Select
            mode="multiple"
            allowClear
            loading={playersLoading}
            placeholder="Players registered in this tournament"
            options={tournamentPlayers?.map((p) => ({
              value: p.fantasyPlayerId,
              label: `#${p.fantasyPlayerId} ${p.nickname}`,
            }))}
          />
        </Form.Item>
      ) : null}
      <Typography.Text strong>Rarity configs (count per tier)</Typography.Text>
      <Form.List name="rarityConfigs">
        {(fields, { add, remove }) => (
          <>
            {fields.map(({ key, name, ...rest }) => (
              <Space key={key} align="baseline" wrap>
                <Form.Item
                  {...rest}
                  name={[name, 'rarity']}
                  rules={[{ required: true }]}
                >
                  <Select options={rarityOptions} />
                </Form.Item>
                <Form.Item
                  {...rest}
                  name={[name, 'cardsCount']}
                  rules={[{ required: true }]}
                >
                  <InputNumber min={1} />
                </Form.Item>
                <MinusCircleOutlined onClick={() => remove(name)} />
              </Space>
            ))}
            <Form.Item>
              <Button type="dashed" onClick={() => add()} icon={<PlusOutlined />}>
                Add rarity row
              </Button>
            </Form.Item>
          </>
        )}
      </Form.List>
      <Form.Item>
        <Button type="primary" htmlType="submit" loading={loading}>
          Save
        </Button>
      </Form.Item>
    </Form>
  )
}
