import type { Rarity } from './types'

export interface CardPackRarityConfigDto {
  rarity: Rarity
  cardsCount: number
}

export interface CreateCardPackRequest {
  name: string
  tournamentId: number
  active?: boolean
  autoGenerated?: boolean
  priceFantiki?: number
  /** Free opens per user for this pack (only when price is positive). */
  freeOpensPerUser?: number
  useAllTournamentPlayers?: boolean
  playerIds?: number[] | null
  rarityConfigs: CardPackRarityConfigDto[]
}

export interface UpdateCardPackRequest {
  name?: string | null
  active?: boolean | null
  autoGenerated?: boolean | null
  priceFantiki?: number | null
  freeOpensPerUser?: number | null
  useAllTournamentPlayers?: boolean | null
  playerIds?: number[] | null
  rarityConfigs?: CardPackRarityConfigDto[] | null
}

export interface UpdateCardPackPlayersRequest {
  playerIds: number[]
}
