import type { Rarity } from './types'

export interface CardPackRarityConfigDto {
  rarity: Rarity
  cardsCount: number
}

export interface CreateCardPackRequest {
  name: string
  tournamentId: number
  active?: boolean
  autoGenerated?: boolean
  priceFantiki?: number
  /** Free opens per user for this pack (only when price is positive). */
  freeOpensPerUser?: number
  /** Max total pack opens per user; 0 = unlimited. */
  maxOpensPerUser?: number
  /** RNG pool for this pack; empty = global canAppearOnRandomCards pool. */
  achievementIds?: string[]
  useAllTournamentPlayers?: boolean
  playerIds?: number[] | null
  rarityConfigs: CardPackRarityConfigDto[]
}

export interface UpdateCardPackRequest {
  name?: string | null
  active?: boolean | null
  autoGenerated?: boolean | null
  priceFantiki?: number | null
  freeOpensPerUser?: number | null
  maxOpensPerUser?: number | null
  achievementIds?: string[] | null
  useAllTournamentPlayers?: boolean | null
  playerIds?: number[] | null
  rarityConfigs?: CardPackRarityConfigDto[] | null
}

export interface UpdateCardPackPlayersRequest {
  playerIds: number[]
}
