export type TournamentStatus = 'DRAFT' | 'ACTIVE' | 'FINISHED'

export type TournamentKind = 'STANDALONE' | 'POLEMICA_COMPETITION'

export type SeriesStatus = 'UPCOMING' | 'ACTIVE' | 'SCORING' | 'FINISHED'

export type Rarity = 'COMMON' | 'RARE' | 'EPIC' | 'LEGENDARY'

export type OccurrenceType = 'ONCE_PER_GAME' | 'MULTIPLE_PER_GAME'

export type AdminRole = 'ADMIN' | 'MODERATOR'

export interface AdminMeDto {
  username: string
  role: AdminRole
}

/** `achievement.id` from the backend catalog (Flyway V10: sniper, voteForBlack, …). */
export type AchievementId = string

export interface AchievementAdminDto {
  id: string
  name: string
  description: string | null
  bonusPoints: number
  occurrenceType: OccurrenceType
  applicableRoles: string[]
  canAppearOnRandomCards: boolean
}

export interface UserProfileDto {
  id: number
  telegramId: number
  username: string | null
  firstName: string | null
  displayName: string | null
  createdAt: string
  fantiki: number
}

export interface BroadcastAcceptedDto {
  recipientCount: number
}

/** Admin user list row; cardsInSeries is null when no tournament+series filter is applied. */
export interface AdminUserListItemDto {
  id: number
  telegramId: number
  username: string | null
  displayName: string | null
  fantiki: number
  cardsInSeries: number | null
}

export interface ActiveSeriesBriefDto {
  id: number
  name: string
  status: SeriesStatus
}

export interface TournamentDto {
  id: number
  name: string
  description: string | null
  status: TournamentStatus
  kind: TournamentKind
  polemicaCompetitionId: number | null
  createdAt: string
  /** Non-finished series; set on list tournaments. Omitted on single-tournament responses. */
  activeSeries?: ActiveSeriesBriefDto[]
}

export interface TournamentPlayerDto {
  id: number
  tournamentId: number
  fantasyPlayerId: number
  polemicaUserId: number
  nickname: string
  photoUrl: string | null
  /** If true, player is not included in random pack draws for this tournament. */
  excludedFromPackPool: boolean
}

export interface TournamentDetailDto extends TournamentDto {
  players: TournamentPlayerDto[]
}

export interface SeriesDto {
  id: number
  tournamentId: number
  name: string
  namePrefix: string | null
  gameNumFrom: number | null
  gameNumTo: number | null
  /** POLEMICA_COMPETITION filter: 0/1/2, null = all phases. */
  gamePhase: number | null
  /** STANDALONE filter by game.started calendar day, format YYYY-MM-DD; null = all days. */
  gameStartedOn: string | null
  status: SeriesStatus
  startsAt: string
  teamDeadline: string
  finalized: boolean
  /** Games synced from Polemica (`series_game` rows). */
  syncedGamesCount: number
  /** Games with calculated fantasy scores (`scored`). */
  scoredGamesCount: number
  /** tournament_player.id assigned to this series */
  tournamentPlayerIds: number[]
}

export interface SeriesPlayerMarketplaceUnlistResultDto {
  tournamentPlayerId: number
  fantasyPlayerId: number
  playerNickname: string
  cancelledListings: number
}

export interface EconomyConfigItemDto {
  key: string
  value: string
  description: string | null
}

export interface UpdateEconomyConfigRequest {
  value: string
}

export interface BulkUpdateEconomyConfigRequest {
  items: { key: string; value: string }[]
}

export interface SeriesFinalizationResultDto {
  rewardsDistributed: number
  cardsDecremented: number
}

export interface StartedSeriesEntryDto {
  seriesId: number
  name: string
  tournamentName: string
  previousStatus: string
}

export interface SkippedSeriesEntryDto {
  seriesId: number
  reason: string
}

export interface BatchStartSeriesResponseDto {
  startedSeries: StartedSeriesEntryDto[]
  skipped: SkippedSeriesEntryDto[]
  notificationRecipientCount: number
}

export interface CardTemplateAchievementDto {
  id: number
  achievementId: string
  achievementName: string
  bonusPoints: number
}

export interface CardTemplateDto {
  id: number
  fantasyPlayerId: number
  rarity: Rarity
  imageUrl: string | null
  description: string | null
  achievements: CardTemplateAchievementDto[]
}

export interface CardPackRarityConfigResponseDto {
  id: number
  rarity: Rarity
  cardsCount: number
}

export interface CardSkinDto {
  id: number
  code: string
  name: string
}

export interface CardPackDto {
  id: number
  name: string
  tournamentId: number
  active: boolean
  autoGenerated: boolean
  priceFantiki: number
  freeOpensPerUser: number
  maxOpensPerUser: number
  achievementIds: string[]
  useAllTournamentPlayers: boolean
  playerIds: number[]
  rarityConfigs: CardPackRarityConfigResponseDto[]
  skinId: number | null
  skinCode: string | null
}

export interface UserCardDto {
  id: number
  telegramUserId: number
  cardTemplateId: number
  acquiredAt: string
  sourceCardPackId: number | null
}

export interface OpenPackResultDto {
  userCards: UserCardDto[]
}

export interface PairAnalysisDto {
  userATelegramId: number
  userBTelegramId: number
  tradesAtoB: number
  tradesTotalAtoB: number
  tradesBtoA: number
  tradesTotalBtoA: number
  netTransfer: number
  bidirectional: boolean
  cleared: boolean
  clearedAt: string | null
  clearedNote: string | null
}

export interface PairTradeDto {
  listingId: number
  price: number
  sellerReceived: number
  createdAt: string
  soldAt: string | null
  sellerTelegramId: number
  buyerTelegramId: number
  userCardId: number
  playerName: string
  rarity: Rarity
  currentOwnerTelegramId: number
  /** False if the card was resold: not deleted at pair ban; seller net is still recovered. */
  buyerStillOwnsCard: boolean
  complaintsCount: number
}

export interface PairTradesUserBriefDto {
  username: string | null
  telegramId: number
  displayName: string
  fantiki: number
}

export interface PairTradesResultDto {
  userA: PairTradesUserBriefDto
  userB: PairTradesUserBriefDto
  trades: PairTradeDto[]
  totalTrades: number
  totalGrossFantiki: number
  totalSellerReceived: number
}

export interface BanPairConfiscatedCardDto {
  userCardId: number
  playerName: string
  rarity: Rarity
}

export interface BanPairUserResultDto {
  telegramId: number
  displayName: string
  fantikiConfiscated: number
  newBalance: number
  cardsConfiscated: BanPairConfiscatedCardDto[]
  listingsCancelled: number
}

export interface BanPairResultDto {
  userA: BanPairUserResultDto
  userB: BanPairUserResultDto
  reason: string
}

export interface BanPairPreviewUserDto {
  telegramId: number
  displayName: string
  balance: number
  fantikiToConfiscate: number
  balanceAfter: number
  cardsToConfiscate: BanPairConfiscatedCardDto[]
}

export interface BanPairPreviewDto {
  userA: BanPairPreviewUserDto
  userB: BanPairPreviewUserDto
}

export interface PairSanctionHistoryItemDto {
  id: number
  createdAt: string
  reason: string
  userLowTelegramId: number
  userHighTelegramId: number
  userLowDisplayName: string
  userHighDisplayName: string
  fantikiTakenLow: number
  fantikiTakenHigh: number
  cardsCountLow: number
  cardsCountHigh: number
}

export interface PagedPairSanctionHistoryDto {
  content: PairSanctionHistoryItemDto[]
  page: number
  size: number
  totalElements: number
  totalPages: number
}

export interface TransactionParticipantDto {
  telegramId: number
  displayName: string
}

export interface ComplainedTransactionDto {
  listingId: number
  playerName: string
  rarity: Rarity
  price: number
  createdAt: string
  soldAt: string
  seller: TransactionParticipantDto
  buyer: TransactionParticipantDto
  complaintsCount: number
  sanctioned: boolean
}

export interface PagedComplainedTransactionsDto {
  content: ComplainedTransactionDto[]
  totalElements: number
  page: number
  size: number
  totalPages: number
}

export interface TransactionComplaintDetailDto {
  userId: number
  displayName: string
  telegramId: number
  complainedAt: string
}

export interface ConcurrentListingDto {
  listingId: number
  sellerDisplayName: string
  sellerTelegramId: number
  price: number
  createdAt: string
  soldAt: string | null
  active: boolean
  sameTemplate: boolean
}

export interface TransactionMarketContextDto {
  listingCreatedAt: string
  concurrentSameTemplate: ConcurrentListingDto[]
  concurrentSamePlayerRarity: ConcurrentListingDto[]
}

export interface TransactionComplaintsListDto {
  complaints: TransactionComplaintDetailDto[]
  marketContext: TransactionMarketContextDto
}

export interface BanDurationRequest {
  days: number
}

export interface SanctionTransactionRequest {
  reason: string
  sellerFine: number
  buyerFine: number
  complainantReward: number
  banSeller: BanDurationRequest | null
  banBuyer: BanDurationRequest | null
}

export interface SanctionTransactionResultDto {
  listingId: number
  sellerFined: number
  sellerNewBalance: number
  sellerBannedUntil: string | null
  buyerFined: number
  buyerNewBalance: number
  buyerBannedUntil: string | null
  complainantsRewarded: number
  totalRewardPaid: number
}

export interface UserByComplaintsDto {
  telegramId: number
  displayName: string
  totalComplaints: number
  transactionsWithComplaints: number
  avgComplaintsPerTransaction: number
  sanctionedTransactions: number
  marketplaceBanned: boolean
  marketplaceBannedUntil: string | null
}

export interface PagedUsersByComplaintsDto {
  content: UserByComplaintsDto[]
  totalElements: number
  page: number
  size: number
  totalPages: number
}

export interface BanUserRequest {
  days: number | null
}
