WITH seed(code, category, condition_type, target_value, chain_group, chain_level, title, description, rarity, display_order) AS (
    VALUES
    ('team_submit_1','PARTICIPATION','TEAMS_SUBMITTED',1,'team_submit',1,'Первый состав','Создать первую команду в любой лиге','COMMON',10),
    ('team_submit_5','PARTICIPATION','TEAMS_SUBMITTED',5,'team_submit',2,'Регулярный участник','Создать команды в 5 лигах серий','COMMON',20),
    ('team_submit_15','PARTICIPATION','TEAMS_SUBMITTED',15,'team_submit',3,'В расписании','Создать команды в 15 лигах серий','RARE',30),
    ('team_submit_30','PARTICIPATION','TEAMS_SUBMITTED',30,'team_submit',4,'Стабильный менеджер','Создать команды в 30 лигах серий','EPIC',40),
    ('team_submit_50','PARTICIPATION','TEAMS_SUBMITTED',50,'team_submit',5,'Сезонный менеджер','Создать команды в 50 лигах серий','EPIC',50),
    ('team_submit_100','PARTICIPATION','TEAMS_SUBMITTED',100,'team_submit',6,'Марафон менеджера','Создать команды в 100 лигах серий','LEGENDARY',60),
    ('team_submit_150','PARTICIPATION','TEAMS_SUBMITTED',150,'team_submit',7,'Элитный менеджер','Создать команды в 150 лигах серий','LEGENDARY',70),
    ('dual_league_1','PARTICIPATION','DUAL_LEAGUE_SERIES',1,'dual_league',1,'Двойная заявка','В одной серии создать команды в MAIN и BUDGET','COMMON',80),
    ('dual_league_10','PARTICIPATION','DUAL_LEAGUE_SERIES',10,'dual_league',2,'Две стратегии','В 10 разных сериях создать команды в MAIN и BUDGET','RARE',90),
    ('dual_league_25','PARTICIPATION','DUAL_LEAGUE_SERIES',25,'dual_league',3,'Гибкий план','В 25 разных сериях создать команды в MAIN и BUDGET','EPIC',100),
    ('dual_league_50','PARTICIPATION','DUAL_LEAGUE_SERIES',50,'dual_league',4,'Мастер двух лиг','В 50 разных сериях создать команды в MAIN и BUDGET','LEGENDARY',110),

    ('budget_team_1','BUDGET','BUDGET_TEAMS_SUBMITTED',1,'budget_team',1,'Первый бюджет','Создать первую команду в BUDGET','COMMON',210),
    ('budget_team_5','BUDGET','BUDGET_TEAMS_SUBMITTED',5,'budget_team',2,'Бюджетный старт','Создать команду в BUDGET 5 раз','COMMON',220),
    ('budget_team_15','BUDGET','BUDGET_TEAMS_SUBMITTED',15,'budget_team',3,'Экономный стратег','Создать команду в BUDGET 15 раз','RARE',230),
    ('budget_team_30','BUDGET','BUDGET_TEAMS_SUBMITTED',30,'budget_team',4,'Мастер бюджета','Создать команду в BUDGET 30 раз','EPIC',240),
    ('budget_team_50','BUDGET','BUDGET_TEAMS_SUBMITTED',50,'budget_team',5,'Бюджетная система','Создать команду в BUDGET 50 раз','EPIC',250),
    ('budget_team_100','BUDGET','BUDGET_TEAMS_SUBMITTED',100,'budget_team',6,'Бюджетный марафон','Создать команду в BUDGET 100 раз','LEGENDARY',260),
    ('budget_team_150','BUDGET','BUDGET_TEAMS_SUBMITTED',150,'budget_team',7,'Элита бюджета','Создать команду в BUDGET 150 раз','LEGENDARY',270),
    ('budget_win_1','BUDGET','BUDGET_WINS',1,'budget_win',1,'Бюджетная победа','Победить в BUDGET-лиге завершенной серии','RARE',280),
    ('budget_win_3','BUDGET','BUDGET_WINS',3,'budget_win',2,'Бюджетный победитель','Победить в BUDGET 3 раза','EPIC',290),
    ('budget_win_10','BUDGET','BUDGET_WINS',10,'budget_win',3,'Чемпион бюджета','Победить в BUDGET 10 раз','LEGENDARY',300),
    ('budget_win_25','BUDGET','BUDGET_WINS',25,'budget_win',4,'Бюджетная династия','Победить в BUDGET 25 раз','LEGENDARY',310),
    ('budget_top10_5','BUDGET','BUDGET_TOP10',5,'budget_top10',1,'Бюджетный топ','5 раз попасть в топ-10 BUDGET','RARE',320),
    ('budget_top10_15','BUDGET','BUDGET_TOP10',15,'budget_top10',2,'Бюджетная стабильность','15 раз попасть в топ-10 BUDGET','EPIC',330),
    ('budget_top10_30','BUDGET','BUDGET_TOP10',30,'budget_top10',3,'Бюджетная вершина','30 раз попасть в топ-10 BUDGET','EPIC',340),
    ('budget_top10_50','BUDGET','BUDGET_TOP10',50,'budget_top10',4,'Бюджетная легенда','50 раз попасть в топ-10 BUDGET','LEGENDARY',350),

    ('series_win_1','RESULTS','SERIES_WINS',1,'series_win',1,'Первая победа','Победить в любой лиге завершенной серии','RARE',410),
    ('series_win_3','RESULTS','SERIES_WINS',3,'series_win',2,'Серийный победитель','Победить в 3 лигах серий','RARE',420),
    ('series_win_10','RESULTS','SERIES_WINS',10,'series_win',3,'Династия','Победить в 10 лигах серий','EPIC',430),
    ('series_win_25','RESULTS','SERIES_WINS',25,'series_win',4,'Большая династия','Победить в 25 лигах серий','LEGENDARY',440),
    ('series_win_50','RESULTS','SERIES_WINS',50,'series_win',5,'Элитная династия','Победить в 50 лигах серий','LEGENDARY',450),
    ('top3_5','RESULTS','TOP3_FINISHES',5,'top3',1,'На пьедестале','5 раз попасть в топ-3','RARE',460),
    ('top3_15','RESULTS','TOP3_FINISHES',15,'top3',2,'Постоянный пьедестал','15 раз попасть в топ-3','EPIC',470),
    ('top3_30','RESULTS','TOP3_FINISHES',30,'top3',3,'Пьедестальная серия','30 раз попасть в топ-3','EPIC',480),
    ('top3_50','RESULTS','TOP3_FINISHES',50,'top3',4,'Мастер пьедестала','50 раз попасть в топ-3','LEGENDARY',490),
    ('top10_10','RESULTS','TOP10_OR_HALF_FINISHES',10,'top10',1,'В верхней группе','10 раз попасть в топ-10 или верхнюю половину','RARE',500),
    ('top10_25','RESULTS','TOP10_OR_HALF_FINISHES',25,'top10',2,'Верхняя группа','25 раз попасть в топ-10 или верхнюю половину','EPIC',510),
    ('top10_50','RESULTS','TOP10_OR_HALF_FINISHES',50,'top10',3,'Стабильный топ','50 раз попасть в топ-10 или верхнюю половину','EPIC',520),
    ('top10_100','RESULTS','TOP10_OR_HALF_FINISHES',100,'top10',4,'Мастер верхней группы','100 раз попасть в топ-10 или верхнюю половину','LEGENDARY',530),
    ('top_quarter_10','RESULTS','TOP_QUARTER_FINISHES',10,'top_quarter',1,'Стабильный результат','10 раз попасть в верхние 25% leaderboard','EPIC',540),
    ('top_quarter_25','RESULTS','TOP_QUARTER_FINISHES',25,'top_quarter',2,'Уверенный результат','25 раз попасть в верхние 25% leaderboard','EPIC',550),
    ('top_quarter_50','RESULTS','TOP_QUARTER_FINISHES',50,'top_quarter',3,'Эталон стабильности','50 раз попасть в верхние 25% leaderboard','LEGENDARY',560),
    ('top_quarter_100','RESULTS','TOP_QUARTER_FINISHES',100,'top_quarter',4,'Легенда стабильности','100 раз попасть в верхние 25% leaderboard','LEGENDARY',570),

    ('cards_total_10','COLLECTION','CARDS_OWNED_TOTAL',10,'cards_total',1,'Первая полка','Владеть 10 активными картами после запуска','COMMON',610),
    ('cards_total_30','COLLECTION','CARDS_OWNED_TOTAL',30,'cards_total',2,'Коллекционер','Владеть 30 активными картами после запуска','RARE',620),
    ('cards_total_100','COLLECTION','CARDS_OWNED_TOTAL',100,'cards_total',3,'Большая коллекция','Владеть 100 активными картами после запуска','EPIC',630),
    ('cards_total_200','COLLECTION','CARDS_OWNED_TOTAL',200,'cards_total',4,'Глубокая коллекция','Владеть 200 активными картами после запуска','EPIC',640),
    ('cards_total_350','COLLECTION','CARDS_OWNED_TOTAL',350,'cards_total',5,'Архивариус коллекции','Владеть 350 активными картами после запуска','LEGENDARY',650),
    ('first_epic','COLLECTION','FIRST_EPIC_CARD',1,'collection_rarity',1,'Эпический дроп','Получить и владеть активной EPIC-картой после запуска','RARE',660),
    ('first_legendary','COLLECTION','FIRST_LEGENDARY_CARD',1,'collection_rarity',2,'Легенда в коллекции','Получить и владеть активной LEGENDARY-картой после запуска','EPIC',670),
    ('first_skin_card','COLLECTION','FIRST_SKIN_CARD',1,'collection_skin',1,'Особый выпуск','Получить или применить активную карту со скином после запуска','RARE',680),
    ('same_player_3_rarities','COLLECTION','SAME_PLAYER_3_RARITIES',1,'same_player_rarities',1,'Любимый игрок','Собрать активные карты одного игрока в 3 редкостях','EPIC',690),

    ('pack_open_1','PACKS','PACKS_OPENED',1,'pack_open',1,'Первый пак','Открыть 1 пак после запуска','COMMON',710),
    ('pack_open_5','PACKS','PACKS_OPENED',5,'pack_open',2,'Пять попыток','Открыть 5 паков после запуска','COMMON',720),
    ('pack_open_15','PACKS','PACKS_OPENED',15,'pack_open',3,'Охота за редкостью','Открыть 15 паков после запуска','RARE',730),
    ('pack_open_30','PACKS','PACKS_OPENED',30,'pack_open',4,'Большое вскрытие','Открыть 30 паков после запуска','EPIC',740),
    ('pack_open_50','PACKS','PACKS_OPENED',50,'pack_open',5,'Пятьдесят паков','Открыть 50 паков после запуска','EPIC',750),
    ('pack_open_100','PACKS','PACKS_OPENED',100,'pack_open',6,'Охотник за паками','Открыть 100 паков после запуска','LEGENDARY',760),
    ('pack_open_150','PACKS','PACKS_OPENED',150,'pack_open',7,'Легенда паков','Открыть 150 паков после запуска','LEGENDARY',770),
    ('pack_epic_drop_1','PACKS','PACK_EPIC_DROP',1,'pack_epic',1,'Эпик из пака','Получить EPIC из пака и владеть этой картой','RARE',780),
    ('legendary_upgrade_1','PACKS','LEGENDARY_UPGRADES',1,'legendary_upgrade',1,'Своими руками','Сделать первый legendary upgrade','EPIC',790),
    ('crafted_legendary_3','PACKS','LEGENDARY_UPGRADES',3,'legendary_upgrade',2,'Мастер апгрейда','Сделать 3 legendary upgrade','LEGENDARY',800),
    ('legendary_upgrade_10','PACKS','LEGENDARY_UPGRADES',10,'legendary_upgrade',3,'Легендарный крафтер','Сделать 10 legendary upgrade','LEGENDARY',810),

    ('market_buy_1','MARKETPLACE','MARKETPLACE_PURCHASES',1,'market_buy',1,'Первая покупка','Купить первую карту на marketplace','COMMON',910),
    ('market_buy_5','MARKETPLACE','MARKETPLACE_PURCHASES',5,'market_buy',2,'Охотник за картами','Купить 5 карт на marketplace','RARE',920),
    ('market_buy_15','MARKETPLACE','MARKETPLACE_PURCHASES',15,'market_buy',3,'Рыночный охотник','Купить 15 карт на marketplace','EPIC',930),
    ('market_buy_30','MARKETPLACE','MARKETPLACE_PURCHASES',30,'market_buy',4,'Коллекционер рынка','Купить 30 карт на marketplace','EPIC',940),
    ('market_sell_1','MARKETPLACE','MARKETPLACE_SALES',1,'market_sell',1,'Первая продажа','Продать первую карту на marketplace','COMMON',950),
    ('market_sell_5','MARKETPLACE','MARKETPLACE_SALES',5,'market_sell',2,'Продавец','Продать 5 карт на marketplace','RARE',960),
    ('market_sell_15','MARKETPLACE','MARKETPLACE_SALES',15,'market_sell',3,'Опытный продавец','Продать 15 карт на marketplace','EPIC',970),
    ('market_sell_30','MARKETPLACE','MARKETPLACE_SALES',30,'market_sell',4,'Мастер продаж','Продать 30 карт на marketplace','EPIC',980),
    ('market_watch_1','MARKETPLACE','MARKETPLACE_WATCHES',1,'market_watch',1,'На наблюдении','Создать первый marketplace watch-фильтр','COMMON',990),
    ('market_watch_5','MARKETPLACE','MARKETPLACE_WATCHES',5,'market_watch',2,'Снайпер рынка','Создать 5 marketplace watch-фильтров','RARE',1000),
    ('market_unique_counterparties_5','MARKETPLACE','MARKETPLACE_UNIQUE_COUNTERPARTIES',5,'market_counterparties',1,'Широкий рынок','Провести SOLD-сделки с 5 разными контрагентами','RARE',1010),
    ('market_unique_counterparties_15','MARKETPLACE','MARKETPLACE_UNIQUE_COUNTERPARTIES',15,'market_counterparties',2,'Большой рынок','Провести SOLD-сделки с 15 разными контрагентами','EPIC',1020),
    ('market_unique_counterparties_30','MARKETPLACE','MARKETPLACE_UNIQUE_COUNTERPARTIES',30,'market_counterparties',3,'Рыночная сеть','Провести SOLD-сделки с 30 разными контрагентами','EPIC',1030),

    ('share_profile_1','SOCIAL','SHARE_PROFILE',1,'share_profile',1,'Витрина открыта','Нажать share профиля','COMMON',1110),
    ('share_team_1','SOCIAL','SHARE_TEAM',1,'share_team',1,'Команда наружу','Нажать share команды','COMMON',1120),
    ('compare_open_1','SOCIAL','COMPARE_OPEN',1,'compare_open',1,'Сравнили составы','Открыть compare-view','COMMON',1130),
    ('view_public_profile_5','SOCIAL','PUBLIC_PROFILE_VIEWS',5,'public_profile_views',1,'Скаут','Открыть 5 чужих профилей','COMMON',1140),
    ('view_public_profile_25','SOCIAL','PUBLIC_PROFILE_VIEWS',25,'public_profile_views',2,'Старший скаут','Открыть 25 чужих профилей','RARE',1150)
)
INSERT INTO achievement_definition (
    code, category, condition_type, history_policy, target_value, chain_group, chain_level,
    title, description, rarity, visibility, enabled, tracking_started_at, display_order, updated_at
)
SELECT
    code,
    category,
    condition_type,
    'FROM_ACHIEVEMENTS_LAUNCH',
    target_value,
    chain_group,
    chain_level,
    title,
    description,
    rarity,
    'PUBLIC',
    TRUE,
    now(),
    display_order,
    now()
FROM seed
ON CONFLICT (code) DO UPDATE
SET category = EXCLUDED.category,
    condition_type = EXCLUDED.condition_type,
    history_policy = EXCLUDED.history_policy,
    target_value = EXCLUDED.target_value,
    chain_group = EXCLUDED.chain_group,
    chain_level = EXCLUDED.chain_level,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    rarity = EXCLUDED.rarity,
    visibility = EXCLUDED.visibility,
    enabled = TRUE,
    tracking_started_at = COALESCE(achievement_definition.tracking_started_at, EXCLUDED.tracking_started_at),
    display_order = EXCLUDED.display_order,
    updated_at = now();

WITH catalog(code) AS (
    VALUES
    ('team_submit_1'),('team_submit_5'),('team_submit_15'),('team_submit_30'),('team_submit_50'),('team_submit_100'),('team_submit_150'),
    ('dual_league_1'),('dual_league_10'),('dual_league_25'),('dual_league_50'),
    ('budget_team_1'),('budget_team_5'),('budget_team_15'),('budget_team_30'),('budget_team_50'),('budget_team_100'),('budget_team_150'),
    ('budget_win_1'),('budget_win_3'),('budget_win_10'),('budget_win_25'),
    ('budget_top10_5'),('budget_top10_15'),('budget_top10_30'),('budget_top10_50'),
    ('series_win_1'),('series_win_3'),('series_win_10'),('series_win_25'),('series_win_50'),
    ('top3_5'),('top3_15'),('top3_30'),('top3_50'),
    ('top10_10'),('top10_25'),('top10_50'),('top10_100'),
    ('top_quarter_10'),('top_quarter_25'),('top_quarter_50'),('top_quarter_100'),
    ('cards_total_10'),('cards_total_30'),('cards_total_100'),('cards_total_200'),('cards_total_350'),
    ('first_epic'),('first_legendary'),('first_skin_card'),('same_player_3_rarities'),
    ('pack_open_1'),('pack_open_5'),('pack_open_15'),('pack_open_30'),('pack_open_50'),('pack_open_100'),('pack_open_150'),
    ('pack_epic_drop_1'),('legendary_upgrade_1'),('crafted_legendary_3'),('legendary_upgrade_10'),
    ('market_buy_1'),('market_buy_5'),('market_buy_15'),('market_buy_30'),
    ('market_sell_1'),('market_sell_5'),('market_sell_15'),('market_sell_30'),
    ('market_watch_1'),('market_watch_5'),
    ('market_unique_counterparties_5'),('market_unique_counterparties_15'),('market_unique_counterparties_30'),
    ('share_profile_1'),('share_team_1'),('compare_open_1'),('view_public_profile_5'),('view_public_profile_25')
)
DELETE FROM achievement_reward ar
USING achievement_definition d, catalog c
WHERE ar.achievement_id = d.id
  AND d.code = c.code;

-- LEGENDARY active-pack rewards from the product draft are intentionally downgraded to EPIC until non-pack LEGENDARY reward sources are implemented.
WITH rewards(code, reward_type, amount, reward_code, metadata, display_order) AS (
    VALUES
    ('team_submit_1','FANTIKI',10,NULL,NULL::jsonb,10),
    ('team_submit_5','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',1,'options',3),10),
    ('team_submit_15','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),10),
    ('team_submit_30','BADGE_STYLE',NULL,'stable_manager',NULL::jsonb,10),
    ('team_submit_30','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20),
    ('team_submit_50','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('team_submit_100','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),10),
    ('team_submit_100','COSMETIC_UNLOCK',NULL,'title_marathon_manager',NULL::jsonb,20),
    ('team_submit_150','PROFILE_FRAME',NULL,'stable_manager_elite',NULL::jsonb,10),
    ('team_submit_150','COSMETIC_UNLOCK',NULL,'title_elite_manager',NULL::jsonb,20),
    ('team_submit_150','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),30),
    ('dual_league_1','FANTIKI',25,NULL,NULL::jsonb,10),
    ('dual_league_10','BADGE_STYLE',NULL,'dual_strategy',NULL::jsonb,10),
    ('dual_league_10','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20),
    ('dual_league_25','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('dual_league_50','COSMETIC_UNLOCK',NULL,'dual_strategy_accent',NULL::jsonb,10),
    ('dual_league_50','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),20),

    ('budget_team_1','FANTIKI',10,NULL,NULL::jsonb,10),
    ('budget_team_5','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',1,'options',3),10),
    ('budget_team_15','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),10),
    ('budget_team_30','BADGE_STYLE',NULL,'budget_master',NULL::jsonb,10),
    ('budget_team_30','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',1,'options',3),20),
    ('budget_team_50','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('budget_team_100','COSMETIC_UNLOCK',NULL,'budget_marathon_title',NULL::jsonb,10),
    ('budget_team_100','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),20),
    ('budget_team_150','PROFILE_FRAME',NULL,'budget_master_elite',NULL::jsonb,10),
    ('budget_team_150','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),20),
    ('budget_win_1','BADGE_STYLE',NULL,'budget_winner',NULL::jsonb,10),
    ('budget_win_1','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),20),
    ('budget_win_3','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),10),
    ('budget_win_3','COSMETIC_UNLOCK',NULL,'budget_winner_title',NULL::jsonb,20),
    ('budget_win_10','PROFILE_FRAME',NULL,'budget_winner',NULL::jsonb,10),
    ('budget_win_10','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),20),
    ('budget_win_25','COSMETIC_UNLOCK',NULL,'budget_champion_title',NULL::jsonb,10),
    ('budget_win_25','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),20),
    ('budget_top10_5','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',1,'options',3),10),
    ('budget_top10_15','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('budget_top10_30','BADGE_STYLE',NULL,'budget_top',NULL::jsonb,10),
    ('budget_top10_30','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),20),
    ('budget_top10_50','COSMETIC_UNLOCK',NULL,'budget_top_accent',NULL::jsonb,10),
    ('budget_top10_50','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),20),

    ('series_win_1','BADGE_STYLE',NULL,'series_winner',NULL::jsonb,10),
    ('series_win_1','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),20),
    ('series_win_3','COSMETIC_UNLOCK',NULL,'series_winner_title',NULL::jsonb,10),
    ('series_win_3','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),20),
    ('series_win_10','PROFILE_FRAME',NULL,'dynasty',NULL::jsonb,10),
    ('series_win_10','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),20),
    ('series_win_25','COSMETIC_UNLOCK',NULL,'dynasty_title',NULL::jsonb,10),
    ('series_win_25','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),20),
    ('series_win_50','PROFILE_FRAME',NULL,'dynasty_elite',NULL::jsonb,10),
    ('series_win_50','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),20),
    ('top3_5','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('top3_15','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('top3_30','COSMETIC_UNLOCK',NULL,'podium_title',NULL::jsonb,10),
    ('top3_30','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),20),
    ('top3_50','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),10),
    ('top10_10','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',1,'options',3),10),
    ('top10_25','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('top10_50','COSMETIC_UNLOCK',NULL,'top10_accent',NULL::jsonb,10),
    ('top10_50','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),20),
    ('top10_100','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),10),
    ('top_quarter_10','BADGE_STYLE',NULL,'steady_result',NULL::jsonb,10),
    ('top_quarter_10','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20),
    ('top_quarter_25','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('top_quarter_50','PROFILE_FRAME',NULL,'steady_result',NULL::jsonb,10),
    ('top_quarter_50','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),20),
    ('top_quarter_100','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),10),

    ('cards_total_10','FANTIKI',10,NULL,NULL::jsonb,10),
    ('cards_total_30','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',1,'options',3),10),
    ('cards_total_100','BADGE_STYLE',NULL,'big_collection',NULL::jsonb,10),
    ('cards_total_100','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20),
    ('cards_total_200','COSMETIC_UNLOCK',NULL,'collection_title',NULL::jsonb,10),
    ('cards_total_200','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),20),
    ('cards_total_350','PROFILE_FRAME',NULL,'collector',NULL::jsonb,10),
    ('cards_total_350','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),20),
    ('first_epic','BADGE_STYLE',NULL,'epic_collection',NULL::jsonb,10),
    ('first_epic','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',1,'options',3),20),
    ('first_legendary','BADGE_STYLE',NULL,'legendary_collection',NULL::jsonb,10),
    ('first_legendary','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20),
    ('first_skin_card','BADGE_STYLE',NULL,'special_edition',NULL::jsonb,10),
    ('first_skin_card','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20),
    ('same_player_3_rarities','BADGE_STYLE',NULL,'favorite_player',NULL::jsonb,10),
    ('same_player_3_rarities','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20),

    ('pack_open_1','FANTIKI',10,NULL,NULL::jsonb,10),
    ('pack_open_5','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',1,'options',3),10),
    ('pack_open_15','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),10),
    ('pack_open_30','BADGE_STYLE',NULL,'pack_opener',NULL::jsonb,10),
    ('pack_open_30','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),20),
    ('pack_open_50','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),10),
    ('pack_open_100','PROFILE_FRAME',NULL,'pack_hunter',NULL::jsonb,10),
    ('pack_open_100','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',2,'options',5),20),
    ('pack_open_150','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),10),
    ('pack_epic_drop_1','BADGE_STYLE',NULL,'pack_epic_drop',NULL::jsonb,10),
    ('pack_epic_drop_1','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',1,'options',3),20),
    ('legendary_upgrade_1','BADGE_STYLE',NULL,'crafted_legendary',NULL::jsonb,10),
    ('legendary_upgrade_1','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20),
    ('crafted_legendary_3','COSMETIC_UNLOCK',NULL,'crafter_title',NULL::jsonb,10),
    ('crafted_legendary_3','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),20),
    ('legendary_upgrade_10','PROFILE_FRAME',NULL,'legendary_crafter',NULL::jsonb,10),
    ('legendary_upgrade_10','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),20),

    ('market_buy_1','FANTIKI',10,NULL,NULL::jsonb,10),
    ('market_buy_5','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),10),
    ('market_buy_15','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('market_buy_30','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('market_sell_1','FANTIKI',10,NULL,NULL::jsonb,10),
    ('market_sell_5','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),10),
    ('market_sell_15','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('market_sell_30','COSMETIC_UNLOCK',NULL,'market_seller_title',NULL::jsonb,10),
    ('market_sell_30','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),20),
    ('market_watch_1','FANTIKI',25,NULL,NULL::jsonb,10),
    ('market_watch_5','BADGE_STYLE',NULL,'market_watch',NULL::jsonb,10),
    ('market_watch_5','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',1,'options',3),20),
    ('market_unique_counterparties_5','BADGE_STYLE',NULL,'wide_market',NULL::jsonb,10),
    ('market_unique_counterparties_5','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20),
    ('market_unique_counterparties_15','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','RARE','count',2,'options',5),10),
    ('market_unique_counterparties_30','COSMETIC_UNLOCK',NULL,'market_network_title',NULL::jsonb,10),
    ('market_unique_counterparties_30','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','EPIC','count',1,'options',3),20),

    ('share_profile_1','BADGE_STYLE',NULL,'profile_shared',NULL::jsonb,10),
    ('share_profile_1','FANTIKI',25,NULL,NULL::jsonb,20),
    ('share_team_1','FANTIKI',25,NULL,NULL::jsonb,10),
    ('compare_open_1','FANTIKI',25,NULL,NULL::jsonb,10),
    ('view_public_profile_5','BADGE_STYLE',NULL,'scout',NULL::jsonb,10),
    ('view_public_profile_5','FANTIKI',25,NULL,NULL::jsonb,20),
    ('view_public_profile_25','COSMETIC_UNLOCK',NULL,'scout_title',NULL::jsonb,10),
    ('view_public_profile_25','CARD_CHOICE_ROLL',NULL,NULL,jsonb_build_object('source','ACTIVE_PACKS','rarity','COMMON','count',2,'options',5),20)
)
INSERT INTO achievement_reward (achievement_id, reward_type, amount, reward_code, metadata, display_order)
SELECT d.id, r.reward_type, r.amount, r.reward_code, r.metadata, r.display_order
FROM rewards r
JOIN achievement_definition d ON d.code = r.code;
